version: "3.9"
services:
  redis:
    image: redis:6
    restart: unless-stopped
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: dialog_user
      POSTGRES_DB: dialog
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    hostname: dialog-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: secret